# Generated by Django 4.2 on 2023-06-11 02:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("stock", "0032_stockitem_build_order"),
        ("stock", "0033_auto_20200426_0539"),
    ]

    dependencies = [
        ("stock", "0031_auto_20200422_0209"),
        ("build", "0015_auto_20200425_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="build_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="build.build",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "OK"),
                    (50, "Attention needed"),
                    (55, "Damaged"),
                    (60, "Destroyed"),
                    (70, "Lost"),
                    (85, "Returned"),
                    (110, "Shipped"),
                    (120, "Used for Build"),
                    (130, "Installed in Stock Item"),
                ],
                default=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
