# Generated by Django 3.2.19 on 2023-06-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_auto_20201004_0158'), ('users', '0003_auto_20201005_2227'), ('users', '0004_auto_20210113_1909'), ('users', '0005_owner_model'), ('users', '0006_alter_ruleset_name'), ('users', '0007_alter_ruleset_name')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('part_category', 'Part Categories'), ('part', 'Parts'), ('stock_location', 'Stock Locations'), ('stock', 'Stock Items'), ('build', 'Build Orders'), ('purchase_order', 'Purchase Orders'), ('sales_order', 'Sales Orders')], help_text='Permission set', max_length=50)),
                ('can_view', models.BooleanField(default=True, help_text='Permission to view items', verbose_name='View')),
                ('can_add', models.BooleanField(default=False, help_text='Permission to add items', verbose_name='Add')),
                ('can_change', models.BooleanField(default=False, help_text='Permissions to edit items', verbose_name='Change')),
                ('can_delete', models.BooleanField(default=False, help_text='Permission to delete items', verbose_name='Delete')),
                ('group', models.ForeignKey(help_text='Group', on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='auth.group')),
            ],
            options={
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(fields=('owner_type', 'owner_id'), name='unique_owner'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('part_category', 'Part Categories'), ('part', 'Parts'), ('stocktake', 'Stocktake'), ('stock_location', 'Stock Locations'), ('stock', 'Stock Items'), ('build', 'Build Orders'), ('purchase_order', 'Purchase Orders'), ('sales_order', 'Sales Orders')], help_text='Permission set', max_length=50),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('part_category', 'Part Categories'), ('part', 'Parts'), ('stocktake', 'Stocktake'), ('stock_location', 'Stock Locations'), ('stock', 'Stock Items'), ('build', 'Build Orders'), ('purchase_order', 'Purchase Orders'), ('sales_order', 'Sales Orders'), ('return_order', 'Return Orders')], help_text='Permission set', max_length=50),
        ),
    ]
