# Generated by Django 3.2.14 on 2022-07-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0081_auto_20220717_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partinternalpricebreak',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='partsellpricebreak',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
    ]
