# Generated by Django 4.2 on 2023-06-11 02:44

import InvenTree.fields
import InvenTree.models
import InvenTree.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import part.models
import part.settings
import stdimage.models


class Migration(migrations.Migration):

    replaces = [
        ("part", "0061_auto_20210104_2331"),
        ("part", "0061_auto_20210103_2313"),
        ("part", "0062_merge_20210105_0056"),
        ("part", "0063_bomitem_inherited"),
        ("part", "0064_auto_20210404_2016"),
    ]

    dependencies = [
        ("stock", "0055_auto_20201117_1453"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company", "0031_auto_20210103_2215"),
        ("part", "0060_merge_20201112_1722"),
        ("stock", "0058_stockitem_packaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="default_expiry",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Expiry time (in days) for stock items of this part",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Default Expiry",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="default_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Default supplier part",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_parts",
                to="company.supplierpart",
                verbose_name="Default Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="minimum_stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum allowed stock level",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Minimum Stock",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="units",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stock keeping units for this part",
                max_length=20,
                null=True,
                verbose_name="Units",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="IPN",
            field=models.CharField(
                blank=True,
                help_text="Internal Part Number",
                max_length=100,
                null=True,
                verbose_name="IPN",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="assembly",
            field=models.BooleanField(
                default=part.settings.part_assembly_default,
                help_text="Can this part be built from other parts?",
                verbose_name="Assembly",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="category",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Part category",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="parts",
                to="part.partcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="default_location",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Where is this item normally stored?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_parts",
                to="stock.stocklocation",
                verbose_name="Default Location",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="description",
            field=models.CharField(
                help_text="Part description", max_length=250, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="is_template",
            field=models.BooleanField(
                default=part.settings.part_template_default,
                help_text="Is this part a template part?",
                verbose_name="Is Template",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Part keywords to improve visibility in search results",
                max_length=250,
                null=True,
                verbose_name="Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="link",
            field=InvenTree.fields.InvenTreeURLField(
                blank=True,
                help_text="Link to external URL",
                null=True,
                verbose_name="Link",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(
                help_text="Part name", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Part notes - supports Markdown formatting",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="revision",
            field=models.CharField(
                blank=True,
                help_text="Part revision or version number",
                max_length=100,
                null=True,
                verbose_name="Revision",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="variant_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Is this part a variant of another part?",
                limit_choices_to={"active": True, "is_template": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="part.part",
                verbose_name="Variant Of",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="virtual",
            field=models.BooleanField(
                default=part.settings.part_virtual_default,
                help_text="Is this a virtual part, such as a software product or license?",
                verbose_name="Virtual",
            ),
        ),
        migrations.AddField(
            model_name="bomitem",
            name="inherited",
            field=models.BooleanField(
                default=False,
                help_text="This BOM item is inherited by BOMs for variant parts",
                verbose_name="Inherited",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="BOM line checksum",
                max_length=128,
                verbose_name="Checksum",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="BOM item notes",
                max_length=500,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="optional",
            field=models.BooleanField(
                default=False,
                help_text="This BOM item is optional",
                verbose_name="Optional",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="overage",
            field=models.CharField(
                blank=True,
                help_text="Estimated build wastage quantity (absolute or percentage)",
                max_length=24,
                validators=[InvenTree.validators.validate_overage],
                verbose_name="Overage",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="part",
            field=models.ForeignKey(
                help_text="Select parent part",
                limit_choices_to={"assembly": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom_items",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=5,
                default=1.0,
                help_text="BOM quantity for this BOM item",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="BOM item reference",
                max_length=500,
                verbose_name="Reference",
            ),
        ),
        migrations.AlterField(
            model_name="bomitem",
            name="sub_part",
            field=models.ForeignKey(
                help_text="Select part to be used in BOM",
                limit_choices_to={"component": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in",
                to="part.part",
                verbose_name="Sub part",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="bom_checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boms_checked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="BOM checked by",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="bom_checked_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="BOM checked date"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="bom_checksum",
            field=models.CharField(
                blank=True,
                help_text="Stored BOM checksum",
                max_length=128,
                verbose_name="BOM checksum",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="creation_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Creation Date"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="creation_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                null=True,
                upload_to=part.models.rename_part_image,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts_responible",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible",
            ),
        ),
        migrations.AlterField(
            model_name="partattachment",
            name="attachment",
            field=models.FileField(
                help_text="Select file to attach",
                upload_to=InvenTree.models.rename_attachment,
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="partattachment",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="File comment",
                max_length=100,
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="partattachment",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="partattachment",
            name="upload_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="upload date"
            ),
        ),
        migrations.AlterField(
            model_name="partattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="default_keywords",
            field=models.CharField(
                blank=True,
                help_text="Default keywords for parts in this category",
                max_length=250,
                null=True,
                verbose_name="Default keywords",
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="default_location",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Default location for parts in this category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_categories",
                to="stock.stocklocation",
                verbose_name="Default Location",
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Description (optional)",
                max_length=250,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="name",
            field=models.CharField(
                help_text="Name",
                max_length=100,
                validators=[InvenTree.validators.validate_tree_name],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="partcategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="part.partcategory",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="partcategoryparametertemplate",
            name="category",
            field=models.ForeignKey(
                help_text="Part Category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter_templates",
                to="part.partcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="partcategoryparametertemplate",
            name="default_value",
            field=models.CharField(
                blank=True,
                help_text="Default Parameter Value",
                max_length=500,
                verbose_name="Default Value",
            ),
        ),
        migrations.AlterField(
            model_name="partcategoryparametertemplate",
            name="parameter_template",
            field=models.ForeignKey(
                help_text="Parameter Template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_categories",
                to="part.partparametertemplate",
                verbose_name="Parameter Template",
            ),
        ),
        migrations.AlterField(
            model_name="partparameter",
            name="data",
            field=models.CharField(
                help_text="Parameter Value", max_length=500, verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="partparameter",
            name="part",
            field=models.ForeignKey(
                help_text="Parent Part",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="partparameter",
            name="template",
            field=models.ForeignKey(
                help_text="Parameter Template",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="part.partparametertemplate",
                verbose_name="Template",
            ),
        ),
        migrations.AlterField(
            model_name="partparametertemplate",
            name="name",
            field=models.CharField(
                help_text="Parameter Name",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="partparametertemplate",
            name="units",
            field=models.CharField(
                blank=True,
                help_text="Parameter Units",
                max_length=25,
                verbose_name="Units",
            ),
        ),
        migrations.AlterField(
            model_name="partrelated",
            name="part_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_parts_1",
                to="part.part",
                verbose_name="Part 1",
            ),
        ),
        migrations.AlterField(
            model_name="partrelated",
            name="part_2",
            field=models.ForeignKey(
                help_text="Select Related Part",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_parts_2",
                to="part.part",
                verbose_name="Part 2",
            ),
        ),
        migrations.AlterField(
            model_name="partsellpricebreak",
            name="part",
            field=models.ForeignKey(
                limit_choices_to={"salable": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salepricebreaks",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="partstar",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starred_users",
                to="part.part",
                verbose_name="Part",
            ),
        ),
        migrations.AlterField(
            model_name="partstar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starred_parts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="parttesttemplate",
            name="part",
            field=models.ForeignKey(
                limit_choices_to={"trackable": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_templates",
                to="part.part",
                verbose_name="Part",
            ),
        ),
    ]
