# Generated by Django 3.2.14 on 2022-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_alter_supplierpricebreak_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpricebreak',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
    ]
