# Generated by Django 4.2 on 2023-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("company", "0060_auto_20230519_0344"),
        ("company", "0061_remove_supplierpart_pack_size"),
        ("company", "0062_contact_metadata"),
    ]

    dependencies = [
        ("part", "0111_auto_20230521_1350"),
        ("company", "0059_supplierpart_pack_units"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierpart",
            name="pack_size",
        ),
        migrations.AddField(
            model_name="contact",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON metadata field, for use by external plugins",
                null=True,
                verbose_name="Plugin Metadata",
            ),
        ),
    ]
