# Generated by Django 4.2 on 2023-06-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("order", "0022_salesorderlineitem_part"),
        ("order", "0023_auto_20200420_2309"),
    ]

    dependencies = [
        ("order", "0021_auto_20200420_1010"),
        ("part", "0035_auto_20200406_0045"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderlineitem",
            name="part",
            field=models.ForeignKey(
                help_text="Part",
                limit_choices_to={"salable": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_order_line_items",
                to="part.part",
            ),
        ),
    ]
